name: tabela_treino
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  scoped_model: ^1.1.0
  google_sign_in: ^4.5.9
  
  #firebase dependecies
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  firebase_core:
  cloud_firestore: ^0.16.0
  admob_flutter: ^1.0.1
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.2
  image_picker: 0.6.7+11
  carousel_slider: ^3.0.0
  flutter_speed_dial: ^3.0.5
  flutter_native_admob: ^2.1.0+3
  share: ^2.0.1
  shared_preferences: ^2.0.5
  after_layout: ^1.1.0
  overlay_support: ^1.2.0
  firebase_messaging: 
  in_app_review: 
  flutter_native_splash: ^0.3.2
  menu_button: ^1.4.2+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_admob: ^0.11.0+1

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/app_icon.png"
  image_path_ios: "images/app_icon.png"

  #  integration_test:
  #  sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/google_logo.png
    - images/blank-profile-picture.png
    - images/logo.png
    - images/app_icon.png
    - images/logoBG.png
    - images/logowBG.png
    - images/halter_vetor.png
    - images/halter_vetor_sel.png
    - images/intro_1.png
    - images/intro_2.png
    - images/intro_3.png
    - images/intro_4.png


  fonts:
    - family: Gotham
      fonts:
        - asset: assets/GothamMedium.ttf
        - asset: assets/GothamMediumItalic.ttf
          style: italic
    - family: GothamBold
      fonts:
        - asset: assets/GothamBold.ttf
        - asset: assets/GothamBoldItalic.ttf
    - family: GothamBook
      fonts:
        - asset: assets/GothamBook.ttf
        - asset: assets/GothamBookItalic.ttf
    - family: GothamLight
      fonts:
        - asset: assets/GothamLight.ttf
    - family: GothamThin
      fonts:
        - asset: assets/Gotham-Thin.otf

